### ISSUE TITLE
building tws docker image fails

### ISSUE THREAD

**Issue by karunkrishna** [francoisruty/fruty_trading-automation#1]
Is oracle-java8-installer required? I though tws comes with a standalone java packaged with it
Can I comment this out to get the docker-compose working?

**E: Package 'oracle-java8-installer' has no installation candidate**
ERROR: Service 'tws' failed to build: The command '/bin/sh -c echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections &&   add-apt-repository -y ppa:webupd8team/java &&   apt-get update &&   apt-get install -y oracle-java8-installer &&   rm -rf /var/lib/apt/lists/* &&   rm -rf /var/cache/oracle-jdk8-installer' returned a non-zero code: 100

**Comment by karunkrishna** [comment]
Changing JAVA_PATH to tws jre fixed the problem. Removed oracle installer from dockerfile';

**Comment by francoisruty** [comment]
Hello, this is weird
As you can see in ib-docker/Dockerfile,
the tws Dockerfile originally comes from https://github.com/ryankennedyio/ib-docker
and I didn't have any problem with it

This may be caused by the fact that the Dockerfile uses ib-gateway latest version, which means the version is not fixed, which means new versions may break the dockerfile

but thanks for the solution
