### ISSUE TITLE
Module 'worker' has no attribute 'celery'

### ISSUE THREAD

**Issue by chicago-joe** [francoisruty/fruty_trading-automation#3]
Okay I've struggled with this for half of a day, trying to figure out how to solve this issue because the worker and beat have continued to fail due to relative import "from celery import Celery" within celery.py (worker/celery.py). 

I'm completely stumped on this and have spent way more time that I should have before asking for help haha. Any help would be appreciated.

Once we get this figured out I'll push a better requirements file, a few sql database table create statements, and some examples using pandas / historical data to upload to those tables.

**Comment by francoisruty** [comment]
Hello, I've reverted your PR, I thought it was a working one, PRs need to be fully functional (= I can follow the README.md and everything works as expected).

I advise you to split your work in smaller chunks, and to make sure everything works fine at each step. I myself almost never work on a task for more than 2-3 hours, since I split my work in very small atomic tasks.

This particular error is a very basic python module import error, you will be able to find plenty of answers on StackOverflow (ex: https://stackoverflow.com/questions/13555386/starting-celery-attributeerror-module-object-has-no-attribute-celery)

**Comment by chicago-joe** [comment]
Understood, but if it is a very basic python module import error, can you please fix this and commit your changes?

Even prior to the PR, the code is broken because Python can't import "celery" from celery.

I've looked at the links you sent over, and I do appreciate the help. I still have not been able to get it to work unfortunately.

**Comment by francoisruty** [comment]
hello, apologies, I hadn't understood that the code was broken even before your PR

can you push your latest branch to the repo, so that I can have a look?

**Comment by chicago-joe** [comment]
No worries haha misunderstandings happen!

I have it fixed and made a few changes, using phpmyadmin for mysql, added a few light grafana dashboards, and used a different TWS-Gateway docker to create a VNC port connection. 

I have a lot of personal client information in the code at the moment, I need to scrape it and then I can upload my changes by the end of the week :)

**Comment by chicago-joe** [comment]
this is fixed in #5  along with additional features and improvements
